import pydantic
from typing import Literal, List


classifier_types = Literal['rent', 'sale']

# Base language for article content generated by AI
base_lang = 'uk'

# Languages to translate into
target_langs = ['cs', 'en', 'ru']


class KeyMetric(pydantic.BaseModel):
    label: str
    value: str
    helper: str


class ArticleTranslation(pydantic.BaseModel):
    """Translated fields for a single locale."""
    title: str
    subtitle: str
    location: str
    body: str
    tags: List[str]
    key_metrics: List[KeyMetric]


class ArticleDraft(pydantic.BaseModel):
    """Base article content in Ukrainian returned by the AI agent."""
    post_type: classifier_types
    slug: str
    title: str
    subtitle: str
    location: str
    body: str
    price: str
    price_on_request: bool
    tags: List[str]
    key_metrics: List[KeyMetric]
